# Generated by Django 4.2.5 on 2023-09-06 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LenguajesFrameworks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=300)),
                ('imagen', models.ImageField(upload_to='imagenes/')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.categoria')),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.lenguajesframeworks')),
            ],
        ),
    ]
