# Generated by Django 4.2.5 on 2023-09-06 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name_plural': 'Categoría'},
        ),
        migrations.AlterModelOptions(
            name='lenguajesframeworks',
            options={'verbose_name_plural': 'Lenguajes / Frameworks'},
        ),
        migrations.AlterModelOptions(
            name='publicacion',
            options={'verbose_name_plural': 'Publicación'},
        ),
    ]
