# Generated by Django 4.2.5 on 2023-09-07 01:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_alter_categoria_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='fechaPublicacn',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
