# Generated by Django 4.2.5 on 2023-09-09 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_publicacion_fechapublicacn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='descripcion',
            field=models.TextField(max_length=250),
        ),
    ]
