# Generated by Django 4.2.5 on 2023-09-16 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_remove_publicacion_framework_publicacion_frameworks'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
