# Generated by Django 4.2.5 on 2023-09-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_publicacion_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='proyecto_imagenes/')),
            ],
        ),
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(max_length=250)),
                ('url', models.URLField(blank=True, null=True)),
                ('frameworks', models.ManyToManyField(to='myApp.lenguajesframeworks')),
                ('imagenes', models.ManyToManyField(blank=True, to='myApp.imagenproyecto')),
            ],
            options={
                'verbose_name_plural': 'Proyectos',
            },
        ),
    ]
