# Generated by Django 4.2.5 on 2023-09-18 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_imagenproyecto_proyectos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyectos',
            name='imagenes',
        ),
        migrations.AddField(
            model_name='proyectos',
            name='imagen',
            field=models.ImageField(default='default.jpg', upload_to='imagenes/'),
        ),
        migrations.DeleteModel(
            name='ImagenProyecto',
        ),
    ]
