# Generated by Django 4.2.5 on 2023-09-19 01:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0010_alter_proyectos_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectos',
            name='fechaPublicacn',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
